---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    cputemp: true
    units: metric
    memory: true
    disk: /
    uptime: true
    refresh: 3000

- search:
    provider: duckduckgo
    focus: true
    showSearchSuggestions: true
    target: _blank

- openweathermap:
    label: Warsaw #optional
    latitude: 52.1951
    longitude: 20.8838
    units: metric # or imperial
    provider: openweathermap
    cache: 5 # Time in minutes to cache API responses, to stay within limits